# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 13:56
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170721_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover_image',
            field=models.ImageField(null=True, upload_to=blog.models.upload_path_handler),
        ),
    ]
