# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 14:36
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=blog.models.upload_path_handler),
        ),
    ]
