# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_author_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
